{
  "timestamp": "2025-08-16T11:59:00.530Z",
  "totalPagesScanned": 20,
  "totalErrors": 8,
  "pagesWithErrors": 2,
  "errorDetails": {
    "/login": [
      "[2025-08-16T11:58:21.459Z]  @firebase/firestore: Firestore (12.1.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unavailable]: The operation could not be completed\nThis typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.",
      "[Error] {\"message\":\"[2025-08-16T11:58:21.459Z]  @firebase/firestore:\",\"stack\":\"Error: [2025-08-16T11:58:21.459Z]  @firebase/firestore:\\n    at console.error (http://localhost:6294/node_modules/.vite/deps/unified-error-handling.js?v=c397ca6c:494:58)\\n    at Logger.defaultLogHandler [as _logHandler] (http://localhost:6294/node_modules/.vite/deps/chunk-3247LBZO.js?v=c397ca6c:1535:20)\\n    at Logger.error (http://localhost:6294/node_modules/.vite/deps/chunk-3247LBZO.js?v=c397ca6c:1603:10)\\n    at __PRIVATE_logError (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:2626:7)\\n    at __PRIVATE_OnlineStateTracker.la (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:13160:16)\\n    at __PRIVATE_OnlineStateTracker.ha (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:13137:54)\\n    at __PRIVATE_onWatchStreamClose (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:13294:47)\\n    at __PRIVATE_PersistentListenStream.close (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:12902:25)\\n    at __PRIVATE_PersistentListenStream.z_ (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:12944:87)\\n    at http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:12932:20\",\"type\":\"Error\",\"timestamp\":1755345501460,\"context\":{\"device\":{\"platform\":\"Linux x86_64\",\"userAgent\":\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/14.5.4 Chrome/130.0.6723.137 Electron/33.2.1 Safari/537.36\",\"language\":\"en-US\",\"viewport\":{\"width\":1280,\"height\":720},\"cookieEnabled\":true,\"onLine\":true,\"screen\":{\"width\":1920,\"height\":1080,\"colorDepth\":24}},\"extra\":{\"source\":\"console.error\",\"consoleArgs\":[\"Firestore (12.1.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unavailable]: The operation could not be completed\\nThis typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.\"],\"url\":\"http://localhost:6294/login\",\"referrer\":\"\",\"parsedStack\":[{\"function\":\"console.error\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/unified-error-handling.js?v=c397ca6c\",\"line\":494,\"column\":58},{\"function\":\"<anonymous>\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/chunk-3247LBZO.js?v=c397ca6c\",\"line\":1535,\"column\":20},{\"function\":\"Logger.error\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/chunk-3247LBZO.js?v=c397ca6c\",\"line\":1603,\"column\":10},{\"function\":\"__PRIVATE_logError\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":2626,\"column\":7},{\"function\":\"__PRIVATE_OnlineStateTracker.la\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":13160,\"column\":16},{\"function\":\"__PRIVATE_OnlineStateTracker.ha\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":13137,\"column\":54},{\"function\":\"__PRIVATE_onWatchStreamClose\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":13294,\"column\":47},{\"function\":\"__PRIVATE_PersistentListenStream.close\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":12902,\"column\":25},{\"function\":\"__PRIVATE_PersistentListenStream.z_\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":12944,\"column\":87},{\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":12932,\"column\":20}]}},\"breadcrumbs\":[{\"message\":\"console.log: üü¢ FCP: 979.20ms\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345500714},{\"message\":\"console.log: üü¢ LCP: 994.50ms\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345500714},{\"message\":\"console.warn: Trace app_initialization not found\",\"category\":\"console\",\"level\":\"warning\",\"timestamp\":1755345500714},{\"message\":\"console.log: Unified offline database service initialized\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345500716},{\"message\":\"console.log: Sync already in progress, skipping...\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345500718},{\"message\":\"console.log: ‚úÖ Notifications initialized successfully\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345500725},{\"message\":\"console.log: üåê Running on web platform - Firebase Kit not needed\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345500725},{\"message\":\"console.log: App updates are only available on native platforms\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345500725},{\"message\":\"console.log: ‚úÖ Notifications initialized successfully\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345500727},{\"message\":\"console.log: üåê Running on web platform - Firebase Kit not needed\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345500727},{\"message\":\"console.log: App updates are only available on native platforms\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345500727},{\"message\":\"console.log: üü¢ LCP: 1396.40ms\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345500992},{\"message\":\"console.warn: [2025-08-16T11:58:21.457Z]  @firebase/firestore: Firestore (12.1.0): WebChannelConnection RPC 'Listen' stream 0x1e827910 transport errored. Name: undefined Message: undefined\",\"category\":\"console\",\"level\":\"warning\",\"timestamp\":1755345501458}],\"level\":\"error\",\"handled\":true,\"source\":\"manual\",\"fingerprint\":\"Error|[2025-08-16T11:58:21.459Z] @firebase/firestore:|at console.error (http://localhost:6294/node_modules/.vite/deps/unified-error-handling.js?v=c397ca6c:494:58)\"}",
      "[2025-08-16T11:58:38.160Z]  @firebase/firestore: Firestore (12.1.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unavailable]: The operation could not be completed\nThis typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.",
      "[Error] {\"message\":\"[2025-08-16T11:58:38.160Z]  @firebase/firestore:\",\"stack\":\"Error: [2025-08-16T11:58:38.160Z]  @firebase/firestore:\\n    at console.error (http://localhost:6294/node_modules/.vite/deps/unified-error-handling.js?v=c397ca6c:494:58)\\n    at Logger.defaultLogHandler [as _logHandler] (http://localhost:6294/node_modules/.vite/deps/chunk-3247LBZO.js?v=c397ca6c:1535:20)\\n    at Logger.error (http://localhost:6294/node_modules/.vite/deps/chunk-3247LBZO.js?v=c397ca6c:1603:10)\\n    at __PRIVATE_logError (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:2626:7)\\n    at __PRIVATE_OnlineStateTracker.la (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:13160:16)\\n    at __PRIVATE_OnlineStateTracker.ha (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:13137:54)\\n    at __PRIVATE_onWatchStreamClose (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:13294:47)\\n    at __PRIVATE_PersistentListenStream.close (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:12902:25)\\n    at __PRIVATE_PersistentListenStream.z_ (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:12944:87)\\n    at http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:12932:20\",\"type\":\"Error\",\"timestamp\":1755345518160,\"context\":{\"device\":{\"platform\":\"Linux x86_64\",\"userAgent\":\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/14.5.4 Chrome/130.0.6723.137 Electron/33.2.1 Safari/537.36\",\"language\":\"en-US\",\"viewport\":{\"width\":1280,\"height\":720},\"cookieEnabled\":true,\"onLine\":true,\"screen\":{\"width\":1920,\"height\":1080,\"colorDepth\":24}},\"extra\":{\"source\":\"console.error\",\"consoleArgs\":[\"Firestore (12.1.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unavailable]: The operation could not be completed\\nThis typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.\"],\"url\":\"http://localhost:6294/login\",\"referrer\":\"\",\"parsedStack\":[{\"function\":\"console.error\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/unified-error-handling.js?v=c397ca6c\",\"line\":494,\"column\":58},{\"function\":\"<anonymous>\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/chunk-3247LBZO.js?v=c397ca6c\",\"line\":1535,\"column\":20},{\"function\":\"Logger.error\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/chunk-3247LBZO.js?v=c397ca6c\",\"line\":1603,\"column\":10},{\"function\":\"__PRIVATE_logError\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":2626,\"column\":7},{\"function\":\"__PRIVATE_OnlineStateTracker.la\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":13160,\"column\":16},{\"function\":\"__PRIVATE_OnlineStateTracker.ha\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":13137,\"column\":54},{\"function\":\"__PRIVATE_onWatchStreamClose\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":13294,\"column\":47},{\"function\":\"__PRIVATE_PersistentListenStream.close\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":12902,\"column\":25},{\"function\":\"__PRIVATE_PersistentListenStream.z_\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":12944,\"column\":87},{\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":12932,\"column\":20}]}},\"breadcrumbs\":[{\"message\":\"console.log: Unified offline database service initialized\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345518017},{\"message\":\"console.log: Sync already in progress, skipping...\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345518053},{\"message\":\"console.warn: [2025-08-16T11:58:38.159Z]  @firebase/firestore: Firestore (12.1.0): WebChannelConnection RPC 'Listen' stream 0x65deae34 transport errored. Name: undefined Message: undefined\",\"category\":\"console\",\"level\":\"warning\",\"timestamp\":1755345518159}],\"level\":\"error\",\"handled\":true,\"source\":\"manual\",\"fingerprint\":\"Error|[2025-08-16T11:58:38.160Z] @firebase/firestore:|at console.error (http://localhost:6294/node_modules/.vite/deps/unified-error-handling.js?v=c397ca6c:494:58)\"}",
      "[2025-08-16T11:58:50.030Z]  @firebase/firestore: Firestore (12.1.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unavailable]: The operation could not be completed\nThis typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.",
      "[Error] {\"message\":\"[2025-08-16T11:58:50.030Z]  @firebase/firestore:\",\"stack\":\"Error: [2025-08-16T11:58:50.030Z]  @firebase/firestore:\\n    at console.error (http://localhost:6294/node_modules/.vite/deps/unified-error-handling.js?v=c397ca6c:494:58)\\n    at Logger.defaultLogHandler [as _logHandler] (http://localhost:6294/node_modules/.vite/deps/chunk-3247LBZO.js?v=c397ca6c:1535:20)\\n    at Logger.error (http://localhost:6294/node_modules/.vite/deps/chunk-3247LBZO.js?v=c397ca6c:1603:10)\\n    at __PRIVATE_logError (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:2626:7)\\n    at __PRIVATE_OnlineStateTracker.la (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:13160:16)\\n    at __PRIVATE_OnlineStateTracker.ha (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:13137:54)\\n    at __PRIVATE_onWatchStreamClose (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:13294:47)\\n    at __PRIVATE_PersistentListenStream.close (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:12902:25)\\n    at __PRIVATE_PersistentListenStream.z_ (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:12944:87)\\n    at http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:12932:20\",\"type\":\"Error\",\"timestamp\":1755345530031,\"context\":{\"device\":{\"platform\":\"Linux x86_64\",\"userAgent\":\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/14.5.4 Chrome/130.0.6723.137 Electron/33.2.1 Safari/537.36\",\"language\":\"en-US\",\"viewport\":{\"width\":1280,\"height\":720},\"cookieEnabled\":true,\"onLine\":true,\"screen\":{\"width\":1920,\"height\":1080,\"colorDepth\":24}},\"extra\":{\"source\":\"console.error\",\"consoleArgs\":[\"Firestore (12.1.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unavailable]: The operation could not be completed\\nThis typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.\"],\"url\":\"http://localhost:6294/login\",\"referrer\":\"\",\"parsedStack\":[{\"function\":\"console.error\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/unified-error-handling.js?v=c397ca6c\",\"line\":494,\"column\":58},{\"function\":\"<anonymous>\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/chunk-3247LBZO.js?v=c397ca6c\",\"line\":1535,\"column\":20},{\"function\":\"Logger.error\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/chunk-3247LBZO.js?v=c397ca6c\",\"line\":1603,\"column\":10},{\"function\":\"__PRIVATE_logError\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":2626,\"column\":7},{\"function\":\"__PRIVATE_OnlineStateTracker.la\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":13160,\"column\":16},{\"function\":\"__PRIVATE_OnlineStateTracker.ha\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":13137,\"column\":54},{\"function\":\"__PRIVATE_onWatchStreamClose\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":13294,\"column\":47},{\"function\":\"__PRIVATE_PersistentListenStream.close\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":12902,\"column\":25},{\"function\":\"__PRIVATE_PersistentListenStream.z_\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":12944,\"column\":87},{\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":12932,\"column\":20}]}},\"breadcrumbs\":[{\"message\":\"console.warn: Trace app_initialization not found\",\"category\":\"console\",\"level\":\"warning\",\"timestamp\":1755345529239},{\"message\":\"console.log: Unified offline database service initialized\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345529255},{\"message\":\"console.log: Sync already in progress, skipping...\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345529261},{\"message\":\"console.log: üü¢ LCP: 1199.50ms\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345529540},{\"message\":\"console.warn: [2025-08-16T11:58:50.030Z]  @firebase/firestore: Firestore (12.1.0): WebChannelConnection RPC 'Listen' stream 0x852b52a8 transport errored. Name: undefined Message: undefined\",\"category\":\"console\",\"level\":\"warning\",\"timestamp\":1755345530030}],\"level\":\"error\",\"handled\":true,\"source\":\"manual\",\"fingerprint\":\"Error|[2025-08-16T11:58:50.030Z] @firebase/firestore:|at console.error (http://localhost:6294/node_modules/.vite/deps/unified-error-handling.js?v=c397ca6c:494:58)\"}"
    ],
    "/settings/profile": [
      "[2025-08-16T11:58:54.210Z]  @firebase/firestore: Firestore (12.1.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unavailable]: The operation could not be completed\nThis typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.",
      "[Error] {\"message\":\"[2025-08-16T11:58:54.210Z]  @firebase/firestore:\",\"stack\":\"Error: [2025-08-16T11:58:54.210Z]  @firebase/firestore:\\n    at console.error (http://localhost:6294/node_modules/.vite/deps/unified-error-handling.js?v=c397ca6c:494:58)\\n    at Logger.defaultLogHandler [as _logHandler] (http://localhost:6294/node_modules/.vite/deps/chunk-3247LBZO.js?v=c397ca6c:1535:20)\\n    at Logger.error (http://localhost:6294/node_modules/.vite/deps/chunk-3247LBZO.js?v=c397ca6c:1603:10)\\n    at __PRIVATE_logError (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:2626:7)\\n    at __PRIVATE_OnlineStateTracker.la (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:13160:16)\\n    at __PRIVATE_OnlineStateTracker.ha (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:13137:54)\\n    at __PRIVATE_onWatchStreamClose (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:13294:47)\\n    at __PRIVATE_PersistentListenStream.close (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:12902:25)\\n    at __PRIVATE_PersistentListenStream.z_ (http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:12944:87)\\n    at http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c:12932:20\",\"type\":\"Error\",\"timestamp\":1755345534210,\"context\":{\"device\":{\"platform\":\"Linux x86_64\",\"userAgent\":\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/14.5.4 Chrome/130.0.6723.137 Electron/33.2.1 Safari/537.36\",\"language\":\"en-US\",\"viewport\":{\"width\":1280,\"height\":720},\"cookieEnabled\":true,\"onLine\":true,\"screen\":{\"width\":1920,\"height\":1080,\"colorDepth\":24}},\"extra\":{\"source\":\"console.error\",\"consoleArgs\":[\"Firestore (12.1.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unavailable]: The operation could not be completed\\nThis typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.\"],\"url\":\"http://localhost:6294/settings/profile\",\"referrer\":\"\",\"parsedStack\":[{\"function\":\"console.error\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/unified-error-handling.js?v=c397ca6c\",\"line\":494,\"column\":58},{\"function\":\"<anonymous>\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/chunk-3247LBZO.js?v=c397ca6c\",\"line\":1535,\"column\":20},{\"function\":\"Logger.error\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/chunk-3247LBZO.js?v=c397ca6c\",\"line\":1603,\"column\":10},{\"function\":\"__PRIVATE_logError\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":2626,\"column\":7},{\"function\":\"__PRIVATE_OnlineStateTracker.la\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":13160,\"column\":16},{\"function\":\"__PRIVATE_OnlineStateTracker.ha\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":13137,\"column\":54},{\"function\":\"__PRIVATE_onWatchStreamClose\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":13294,\"column\":47},{\"function\":\"__PRIVATE_PersistentListenStream.close\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":12902,\"column\":25},{\"function\":\"__PRIVATE_PersistentListenStream.z_\",\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":12944,\"column\":87},{\"file\":\"http://localhost:6294/node_modules/.vite/deps/firebase_firestore.js?v=c397ca6c\",\"line\":12932,\"column\":20}]}},\"breadcrumbs\":[{\"message\":\"console.warn: Trace app_initialization not found\",\"category\":\"console\",\"level\":\"warning\",\"timestamp\":1755345533432},{\"message\":\"console.log: Unified offline database service initialized\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345533433},{\"message\":\"console.log: Sync already in progress, skipping...\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345533438},{\"message\":\"console.log: üü¢ LCP: 1129.80ms\",\"category\":\"console\",\"level\":\"info\",\"timestamp\":1755345533626},{\"message\":\"console.warn: [2025-08-16T11:58:54.209Z]  @firebase/firestore: Firestore (12.1.0): WebChannelConnection RPC 'Listen' stream 0x4a8e502a transport errored. Name: undefined Message: undefined\",\"category\":\"console\",\"level\":\"warning\",\"timestamp\":1755345534210}],\"level\":\"error\",\"handled\":true,\"source\":\"manual\",\"fingerprint\":\"Error|[2025-08-16T11:58:54.210Z] @firebase/firestore:|at console.error (http://localhost:6294/node_modules/.vite/deps/unified-error-handling.js?v=c397ca6c:494:58)\"}"
    ]
  }
}